### ISSUE TITLE
Issuance Hint

### ISSUE THREAD

**Issue by erickuhn19** [decentralized-identity/presentation-exchange#105]
Without discoverability of Credential Manifests from the DID being standardized, we need a way of hinting to the User Agent of a CM to complete the presentation exchange. 

"issuance": [{ did: "", manifest: "CM_HERE" }, {…}],
        "constraints": {
          "fields": [
            {

**Comment by brentzundel** [comment]
I'm not sure this is a good idea.

I understand the need to find a way to communicate where credentials may be sourced for potential holders of those credentials, but I'm not sure that encumbering the presentation definition with a property that does so would be the best solution.
Considering that the need exists primarily due to to immaturity in the credential ecosystem, the long-term usefulness of such a property would be limited.

It seems to me that rather than normatively including such a property in the spec, it may be better to either:
1. send a separate package alongside the presentation request that contains credential sourcing information, or
2. use a non-standard property to communicate this information

This would allow the need to be fulfilled in the short term, while better solutions for communicating available credentials develop naturally as the ecosystem matures.

**Comment by csuwildcat** [comment]
Will not implement at this time, WG will assess after Credential Manifest/Well-Known work is done.
