### ISSUE TITLE
Subject Holder restriction 

### ISSUE THREAD

**Issue by dtmcg** [decentralized-identity/presentation-exchange#12]
In the case of VC responses, it looks to be assumed that the subject and holder are the same identity. 
Is an explicit selector needed for this (or an explicit exception) e.g. You may hold a vaccination credential for a dog which is the subject of said credential. Or is it recommended that this be handled in business logic.

**Comment by OR13** [comment]
I believe that holder != subject is supported... maybe not in examples, but its not prohibited.

cc @csuwildcat @rado0x54 @glcohen

**Comment by csuwildcat** [comment]
Related to this issue: https://github.com/decentralized-identity/presentation-exchange/issues/24

**Comment by wyc** [comment]
Summary, we want to be able to say:
- We want _you_ to give us your passport directly, we don't want your mom to give us your passport on your behalf.
- We want _you_ to give us _your_ passport, and not your mom's passport.

**Comment by brentzundel** [comment]
PR #84 addresses the first of @wyc 's bullet points.

**Comment by dtmcg** [comment]
@brentzundel `"subject_is_holder": "required"` looks like it would address both points, is theres something missing for the second of @wyc bullet points ?

**Comment by dtmcg** [comment]
This could be considered a relationship expression. (Same for https://github.com/decentralized-identity/presentation-exchange/issues/49)

Brents solution defines the relationships in a course way, which is great for getting a v.0.1.0. 

In the same way we would like (in a future iteration) to have relationship expressions from issues to other identities (https://github.com/decentralized-identity/presentation-exchange/issues/24#issuecomment-666599426), this same kind of relationship specification may be applied here. 
e.g.  `holder == issuer`, `issuer == subject`  may be expressed as well as something more sophisticated `holder == solicitor acting as an agent of the the subject`.

**Comment by brentzundel** [comment]
keeping this issue open, but moving it to `future`  to track the possible more sophisticated methods in future iterations of the spec.

**Comment by dhh1128** [comment]
In reading this comment stream, I am feeling uneasy with the proposed resolution of `subject_is_holder = true`. The reason is that it doesn't address the case of multi-subject credentials like a birth certificate (subjects = mother, child, maybe father, maybe doctor). I think we need something more like `holder_subject_type = "mother"' where we'd be matching against `credentialSubject -> @type = "mother"` or something like that.

**Comment by OR13** [comment]
> In reading this comment stream, I am feeling uneasy with the proposed resolution of `subject_is_holder = true`. The reason is that it doesn't address the case of multi-subject credentials like a birth certificate (subjects = mother, child, maybe father, maybe doctor). I think we need something more like `holder_subject_type = "mother"' where we'd be matching against `credentialSubject -> `@type` = "mother"` or something like that.

Interesting, I agree... it would be better to have the property be something like `allowedSubjectAndHolderTypes`, with a definition like:

if the holder presents a credential containing at least one of the values, and the subject of the credential is the holder this condition is true, otherwise it false.

**Comment by brentzundel** [comment]
I've modified #123 to address this.
