### ISSUE TITLE
ZKP support for "predicate" should be removed from the spec

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/presentation-exchange#175]
in absence of tests that prove that 2 implementations support the feature.

**Comment by OR13** [comment]
If can't be tested, it doesn't belong in a spec.... specs are not for describing "imaginary future systems that nobody has built yet".....

requiring tests, ensures that specs are implementable.

I believe the best case for the "required" predicate is that there are tests that show that it works.

**Comment by brentzundel** [comment]
I don't disagree with the assertion that untestable statements shouldn't be normatively required in a spec.
I am amused at the characterization of predicates as "imaginary future systems that nobody has built yet"

Does this spec have an associated test suite? What test in which framework should be passed by multiple implementers in order to keep predicates?

If support for predicates is removed from the spec, no one who uses Indy credentials will be able to use it. They will continue using their internal proof request format which does support predicates.

**Comment by TomCJones** [comment]
I think purposes should all be more structured. One think that would help is to understand the context = what I would call a federation. So - in the context of e.g.  US FED regulation for kyc or HL7 spec for health care information, etc. They have purposes defined

**Comment by TomCJones** [comment]
does that need to go down to the level of a predicate?  Well how about age-over-20 purpose serving-alcohol

**Comment by csuwildcat** [comment]
Action: Brent will add warnings and clarification to the section that talks about predicate `required`, including recommending not use it unless you know your holders will support the nascent field of ZKP-compatible wallet implementations.
