### ISSUE TITLE
Suggestion: modularize JSON schema

### ISSUE THREAD

**Issue by tlodderstedt** [decentralized-identity/presentation-exchange#230]
"presentation_definition" is defined as top level element in the respective JSON schema, which makes it impossible to incorporate (instantiate) the presentation_definition element in a protocol specific JSON Schema.  We had to create a fork of the current scheme in order to utilize the JSON scheme within OpenID Connect 4 Identity Assurance.

**Comment by csuwildcat** [comment]
I think this should be easy to do, and we can tackle it in the process of the overall componentization of PE Descriptor top-level objects/values

**Comment by JaceHensley** [comment]
@tlodderstedt Can you provide more information about how you are embedding the `presentation_definition` object in your protocol specific target?

**Comment by tlodderstedt** [comment]
sure. We embed presentation_definition within the OIDC claims parameter. 

See https://openid.bitbucket.io/connect/openid-connect-4-verifiable-presentations-1_0.html#name-requesting-verifiable-prese

**Comment by kimdhamilton** [comment]
Thanks @tlodderstedt, this is helpful.

Just to clarify something -- is it true that the "OIDC for VPs" approach never has a need for `descriptor_map` in the response? I don't see it in the spec, but just want to check.

**Comment by tlodderstedt** [comment]
We haven't seen the need so far but are discussing potential benefits with PE authors.

**Comment by kimdhamilton** [comment]
Would appreciate it if the rest of us could be privy to that conversation too...

**Comment by tlodderstedt** [comment]
Me too :-) I requested access to the DIF Slack so we can conduct the conversation there.

**Comment by kimdhamilton** [comment]
Let's make that happen!

The call to modularize PE already resonates with me, and OIDC integration would be a huge bonus. Given the scope of changes needed, incremental revisions like making various fields optional are unlikely to yield a satisfactory result to anyone. This issue seems like a good one to start 

The changes requested for OIDC seem better suited for a PE v2 revision with goals of:
1. using PE objects in a more fine-grained way
	- one use case pointed to by this proposal is incremental exchange of VPs, spread across different phases of the protocol flow
2. simplifications based on assumptions that are possible in a fixed context
	- much of the complexity of PE is needing to enable variation across multiple protocols/transports, which, within the context of a single approach, may seem heavy-handed.
	- e.g., OIDC for VPs is proposing standard terms like "presentation", reducing the need for some levels of indirection provided by PE
3. Support by-reference in addition to id lookups (big question is how this layering happens)
	- i.e., in these use cases, don't need "id" fields because all the information is expressed at the time is needed
	- possibly an emergent description of this more state-/context-aware use of PE objects, i.e. which is another framing of #2, i.e.: some levels of indirection in PE aren't needed because issuer should know based on context

Exactly how this happens is up to the authors of PE v2, where "OIDC for VPs" serves as valuable input. Given the scope of changes requested, PE authors need to think about:
- How this could improve use of PE objects in other contexts besides OIDC
- Layering, i.e. is the base spec a set of useful objects like input descriptors that will appear in higher-level specs
- Framing, i.e. are these different PE profiles?

**Comment by kimdhamilton** [comment]
Quick rathole on IDs, which were troubling me for different reasons than those presented by the OIDC use cases.

What is the expectation of id permanence over time? If id corresponds to a URI, with the expectation of a separate lookup, is this prohibitive for some use cases? Should there be expectation of caching?

**Comment by csuwildcat** [comment]
@kimdhamilton the IDs on input descriptors are just to link the submitted credentials to their descriptors for efficient evaluation, instead of random hit test looping.

**Comment by kimdhamilton** [comment]
right, I was referring to some of the higher-level IDs, but I will cross out that comment because that doesn't belong in this thread.

**Comment by JaceHensley** [comment]
I think this would be perfect for a Discussion https://docs.github.com/en/discussions/quickstart could we turn that on for this repo?

**Comment by kimdhamilton** [comment]
@JaceHensley, that makes sense. @csuwildcat: discussions aren't enabled yet for this repo; could you turn them on?

**Comment by csuwildcat** [comment]
@JaceHensley @kimdhamilton just turned on Discussions

**Comment by kimdhamilton** [comment]
moving some of this discussion (on modularization of PE) to https://github.com/decentralized-identity/presentation-exchange/discussions/236
