### ISSUE TITLE
Add a include/exclude flag to constraints 

### ISSUE THREAD

**Issue by erickuhn19** [decentralized-identity/presentation-exchange#25]
A Relying Party may only want to validate that a Verifiable Credential exists or that a specific attestation within a Verifiable Credential exists, which is an important distinction from a privacy perspective. Not all Relying Parties will want all attestations within a Verifiable Credential. 

This spec is expressive to ask for a VC with a specific attestation to fulfill their requirements but the  user is also under the obligation to send all attestations for that given Verifiable Credential.  Those attestations may include PII and be toxic for the Relying Party to receive and be irrelevant for the user to share. 

Example: 
As a rental community Relying Party, I would like to validate the schema of bank_credentials.json. This schema includes the attestation of is_bank_account = true but it also includes very private data that does not need to be shared like routing_number, account_number etc. As a Relying Party I want to see the is_bank_account attestation but none of the other attestations. 

With that example being stated, I am proposing a flag that goes in the constraints (or where ever is technically the most accurate to solve this issue) that would ask for certain fields to be excluded and other fields to be included. Implementation question: what happens if a attestation does not have a include or exclude flag?

This would make the intentions and full requirements of the Relying Party known to the Client. The Client would then be able to surface a clean permission request for the user to make a decision on. The Client should have a binary decision to make. Remove the 'exclude' attestations and add the 'include' attestations to the Presentation or the request will fail.

**Comment by PranavPillaiMSFT** [comment]
_"A Relying Party may only want to validate that a Verifiable Credential exists or that a specific attestation within a Verifiable Credential exists, which is an important distinction from a privacy perspective."_

^ Agreed, but I don't think we're necessarily doing this in v1. You'll be proving more than that an attestation within a VC exists -- you'll actually be sharing its value.

_"I am proposing a flag that goes in the constraints (or where ever is technically the most accurate to solve this issue) that would ask for certain fields to be excluded and other fields to be included. Implementation question: what happens if a attestation does not have a include or exclude flag?"_

^ I think a simpler implementation (that we've briefly discussed) would be adding an array of the names of claims that you'd like to receive in a request. This solution has no issues of attestations with missing flags, and is generally less verbose / taxing for the RP (they don't need to add the names of attestations that they don't even want)

**Comment by csuwildcat** [comment]
Done
