### ISSUE TITLE
server running error

### ISSUE THREAD

**Issue by SamerW** [decentralized-identity/presentation-exchange#365]
I have got this error while running the command: npx serve build
Any idea?

```
(node:1606) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/awazan/.npm/_npx/aab42732f01924e5/node_modules/serve/build/main.js:130
      url.port = url.port ?? "3000";
                           ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by dtmcg** [comment]
what version of npm are you using ?

**Comment by bumblefudge** [comment]
has anyone been able to replicate this error?

**Comment by dtmcg** [comment]
I successfully ran through this today against the latest version `7cbc95dbb20dc65ec113fb2440f80aa5bf4d079b`
closing issue 
@SamerW if this issue appears again please reopen

**Comment by bumblefudge** [comment]
oh i just realized this is in the spec-up build script?  i believe daniel b said specup had some dependency troubles recently, presumably they've been fixed since 6jan.  for future reference/spec-up bugs, people can just disable spec-up when they build with package.json (it's just the spec-building tool), or we could even disable it in the repo's package.json to pre-empt trouble since people cloning aren't generally interested in seeing the spec built locally :D 

if re-opened we should move this to the spec-up repo!
