### ISSUE TITLE
add data/flow relationship diagram to PE to visualize object flow

### ISSUE THREAD

**Issue by andorsk** [decentralized-identity/presentation-exchange#385]
Proposal here to add a diagram in the PE that shows the standard object relationship and flow. i.e PD, VP, PE, PS, etc between a holder and a verifier. I'm willing to take that up.

**Comment by csuwildcat** [comment]
I'll get you setup with some permissions soon @andorsk

**Comment by brentzundel** [comment]
I think the best course of action would be to make sure @andorsk is added to [The C & C WG Team](https://github.com/orgs/decentralized-identity/teams/cc-wg)
@wyc or @rado0x54 can you add him?

**Comment by andorsk** [comment]
thanks @brentzundel!

**Comment by kimdhamilton** [comment]
@rado0x54 @andorsk @csuwildcat I propose removing the 2.1 milestone label on this

**Comment by kimdhamilton** [comment]
I think we should do the following:

1. Since there are only 2 normative objects (PD and PS), we have a swimlane diagram that shows these flowing between verifier and holder. We'll put this near the beginning of the spec, likely around the intro.
![swimlanes-b31e618b2a3e93fb952bda623640051f](https://github.com/decentralized-identity/presentation-exchange/assets/3945683/ca7aa797-406e-472d-8e32-ba2a6dabde7b)

2. Add one more diagram in the "embed targets" section showing how VP relates to PS and VCs for 2 of the embed targets (Verifiable Presentation and JWTs). It can be as simple as the following:

![swimlanes-b31e618b2a3e93fb952bda623640051f](https://github.com/decentralized-identity/presentation-exchange/assets/3945683/ca407681-26ca-49d2-a980-8054b5bb76c0)

@andorsk @rado0x54 @csuwildcat let me know what you think and I can work it into a PR.

**Comment by kimdhamilton** [comment]
Fixed with #470
