### ISSUE TITLE
refine path descriptions 

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#45]
from #18 
>            // TODO: we can't just list paths in VC JSON this way; we have
>            // to link them to schemas ("if schema A, then path A.x;
>            // if schema B, then path B.y"). Otherwise we create
>            // possible paths that can be exploited to surprising effect.

**Comment by csuwildcat** [comment]
The part of the spec that allowed for specifying multiple schemas assumed that there was not a change in property location or function in the target schemas, for example: two different schemas of subtly different versions, but not any difference between them for the use case/target of the queries. If this is an issue, I would rather simply remove the multiple URI allowance for now and require multiple descriptor entries that redundantly specified constraints, because I feel the addition of schema-to-path matching is a level of complexity we should avoid.

**Comment by csuwildcat** [comment]
Proposal: add descriptive note on the use of schemas and multiple URIs.

**Comment by csuwildcat** [comment]
Closed via merge of https://github.com/decentralized-identity/presentation-exchange/pull/83
