### ISSUE TITLE
Specify a version of JSON Schema

### ISSUE THREAD

**Issue by decentralgabe** [decentralized-identity/presentation-exchange#480]
The examples all use Draft 7, which is old, but widely implemented. I would like to see this enshrined in the spec to reduce implementer confusion and prevent interop issues.

This is coming up in relation to:
* https://github.com/decentralized-identity/presentation-exchange/issues/280
* https://github.com/decentralized-identity/presentation-exchange/issues/303
* https://github.com/openid/OpenID4VP/issues/2

If there are no strong objections I'd like to quickly move to amend 2.1 with this detial.

**Comment by kimdhamilton** [comment]
Thanks @decentralgabe! I reopened #303 since it looks like that was closed without resolution. I remember before cutting the 2.1 release, we asked around extensively because we were told generally of an issue related to JSON schema, but no one submitted details. 

Are you saying that the root cause of all of these is that they use draft 7, but that is not specified? I'm still a bit unclear about the proposed change and how it addresses these.

But yes, if this addresses these problems, we'd welcome a PR (and details about how it relates to the above issues).

**Comment by csuwildcat** [comment]
@kimdhamilton I believe the root cause is they aren't using a current enough version, not one that's too new.

**Comment by decentralgabe** [comment]
Yes I believe implementers were using an older version that lacked some features like oneOf/anyOf. Specifying a draft that supports at least the features mentioned in PE itself should be sufficient to address the concern

**Comment by kimdhamilton** [comment]
Ok, this sounds fantastic -- this has been befuddling me for a while. Please proceed with the PR, and thanks again!

**Comment by decentralgabe** [comment]
https://github.com/decentralized-identity/presentation-exchange/pull/481
